name: go
on: [push]

env:
  GO_VERSION: 1.22.0

jobs:
  # Job for running go linter
  go-lint:
    runs-on: ubuntu-latest
    env:
      # TODO: only required until making the repo public
      SSH_AUTH_SOCK: /tmp/ssh_agent.sock
    steps:
      - name: git clone
        uses: actions/checkout@v4
      - name: set up go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      # TODO: only required until making the repo public
      - name: allow access to private repos
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null || true
          ssh-add - <<< "${{ secrets.NEXTMVBOT_SSH_KEY }}"
          git config --global url."git@github.com:".insteadOf "https://github.com/"
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: v1.56.2
  # Job for running tests
  go-test:
    runs-on: ubuntu-latest
    env:
      # TODO: only required until making the repo public
      SSH_AUTH_SOCK: /tmp/ssh_agent.sock
    steps:
      - name: git clone
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: set up go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      # TODO: only required until making the repo public
      - name: allow access to private repos
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null || true
          ssh-add - <<< "${{ secrets.NEXTMVBOT_SSH_KEY }}"
          git config --global url."git@github.com:".insteadOf "https://github.com/"
      - name: go test
        run: go test ./...
